# Generated by Django 4.2 on 2023-04-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikelBlog', '0004_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
