# Generated by Django 4.2 on 2023-05-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikelBlog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.CharField(default='click Link above to read Blog Post ....', max_length=255),
        ),
    ]
