# Generated by Django 4.2 on 2023-05-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikelBlog', '0011_profile_facebook_profile_hilokal_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='website_url',
        ),
    ]
